services:

  server:
    build:
      context: ./server
    ports:
      - 5555:5555
    container_name: pokemon_image_server
    stdin_open: true
    tty: true
    volumes:
      - ./art/pokemon_art:/server/art/pokemon_art
      - ./art/pokemon_art_256:/server/art/pokemon_art_256
    restart: unless-stopped
