services:

  server:
    build:
      context: ./server
    ports:
      - 4444:4444
    container_name: pokemon_image_server
    stdin_open: true
    tty: true
    volumes:
      - ./pokemon_art:/server/pokemon_art
      - ./pokemon_art_1024:/server/pokemon_art_1024
      - ./pokemon_art_256:/server/pokemon_art_256
    restart: unless-stopped